# Generated by Django 4.0.4 on 2022-06-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Familiares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiares',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
