# Generated by Django 4.0.5 on 2022-06-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Familiares', '0002_familiares_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiares',
            name='fecha_nacimiento',
            field=models.DateTimeField(null=True),
        ),
    ]
